# Site settings
title: "Gavin's Blog"
keyword: "Java"
description: "Focus on Java, Performance Tunning"
email: "haozhonghu@hotmail.com"
author: "Gavin Hu"
baseurl: "/"
url: "http://yourdomain.com"
#twitter_username: jekyllrb
github_username:  "haozhonghu@hotmail.com"

# Build settings
markdown: kramdown
permalink: pretty

# categories
category:
  path: /categories
# archives
monthly_archive:
  path: /archives

